apiVersion: apps/v1
kind: Deployment
metadata:
  name: flashcard-service-deployment
  namespace: henshi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flashcard-service
  template:
    metadata:
      labels:
        app: flashcard-service
    spec:
      containers:
        - name: flashcard-service
          image: ghcr.io/henshiapp/henshi-flashcard-service:latest
          env:
            - name: DATABASE_HOST
              value: "flashcard-service-postgres"
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: flashcard-secrets
                  key: FLASHCARD_DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: flashcard-secrets
                  key: FLASHCARD_DATABASE_PASSWORD
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"