services:
    ##############
    # API        #
    ##############
    api-database:
        container_name: api-database
        image: postgres:17-alpine
        restart: unless-stopped
        healthcheck:
            test: [ "CMD", "pg_isready", "-q", "-d", "henshi", "-U", "postgres" ]
            timeout: 45s
            interval: 3s
            retries: 10
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            TZ: UTC
            PGTZ: UTC
        ports:
            - '5432:5432'
        volumes:
            - api-database-data:/var/lib/postgresql/data

volumes:
    api-database-data:
