apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: henshi
  labels:
    app: web
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3000