apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: henshi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ghcr.io/henshiapp/henshi-web:latest
          env:
            - name: VITE_AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: AUTHORITY

            - name: VITE_AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: CLIENT_ID

            - name: VITE_AUTH0_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: AUDIENCE

            - name: VITE_API_URL
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: URL
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"