apiVersion: v1
kind: Service
metadata:
  name: flashcard-service-service
  labels:
    app: flashcard-service
spec:
  selector:
    app: flashcard-service
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080