apiVersion: v1
kind: Service
metadata:
  name: zitadel-service
  labels:
    app: zitadel
spec:
  selector:
    app: zitadel
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080