apiVersion: v1
kind: Service
metadata:
  name: zitadel-database-service
  labels:
    app: zitadel-db
spec:
  selector:
    app: zitadel-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432