apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: henshi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/henshiapp/henshi-api:7460c18c424866085aa53e230f35539d4e8a4f0d
          env:
            - name: ConnectionStrings__FlashcardsConnectionString
              valueFrom:
                secretKeyRef:
                  name: api-database-secrets
                  key: POSTGRES_CONNECTION_STRING

            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: AUTH0_DOMAIN

            - name: AUTH0_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: AUTH0_AUDIENCE

            - name: DATABASE_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: DATABASE_ENCRYPTION_KEY

            - name: Cors__Origins
              valueFrom:
                configMapKeyRef:
                  name: web-config
                  key: URL
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
